# Generated by Django 2.2.6 on 2019-11-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('IS', 'Info Session'), ('WS', 'Workshop'), ('SJ', 'Study Jam Workshop'), ('HO', 'Hands-on Workshop'), ('HA', 'Hackathon'), ('SS', 'Speaker Session'), ('SC', 'Showcase')], max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=5000)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
