# Generated by Django 2.2.6 on 2019-11-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('E', 'Everyone'), ('A', 'Active Members'), ('C', 'Core Team')], default='E', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('IS', 'Info Session'), ('WS', 'Workshop'), ('SJ', 'Study Jam Workshop'), ('HO', 'Hands-on Workshop'), ('HA', 'Hackathon'), ('SS', 'Speaker Session'), ('SC', 'Showcase'), ('CT', 'Core Team Meeting')], max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
