# Generated by Django 2.2.6 on 2019-11-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20191127_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=3000)),
                ('repository_link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='presentation_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
