# Generated by Django 2.2.6 on 2019-11-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20191127_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('P', 'Public'), ('M', 'Members'), ('C', 'Core Team')], max_length=1),
        ),
    ]
