# Generated by Django 2.2.6 on 2019-11-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20191128_0118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
