# Generated by Django 2.2.6 on 2019-11-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_auto_20191128_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional url of image to display on top of update and on index page.', null=True),
        ),
    ]
