# Generated by Django 2.2.6 on 2019-11-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_auto_20191128_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_notes_link',
            field=models.URLField(blank=True, help_text='An optional link to the meeting notes for the event. This is most likely to an auto-generated Google Docs.', null=True),
        ),
    ]
