# Generated by Django 2.2.6 on 2019-11-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_event_meeting_notes_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='meeting_notes_link',
        ),
        migrations.AddField(
            model_name='event',
            name='meeting_notes_id',
            field=models.URLField(blank=True, help_text='An optional link to the meeting notes for the event. This is most likely to an auto-generated Google Docs.', null=True),
        ),
    ]
