# Generated by Django 2.2.6 on 2019-11-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_auto_20191129_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar_event_id',
            field=models.CharField(blank=True, help_text='The Google Calendar event ID', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='meeting_notes_id',
            field=models.CharField(blank=True, help_text='The ID of the Google Docs meeting notes. This is most likely to an auto-generated Google Docs.', max_length=300, null=True),
        ),
    ]
