# Generated by Django 3.0.1 on 2019-12-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_auto_20191129_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance_code',
            field=models.CharField(default='abcdef', help_text='Random attendance code for members to submit to verify their attendance.', max_length=6),
            preserve_default=False,
        ),
    ]
