# Generated by Django 3.0.1 on 2019-12-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_event_attendance_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='grade',
            field=models.CharField(blank=True, choices=[('Fr', 'Freshman'), ('So', 'Sophomore'), ('Ju', 'Junior'), ('Se', 'Senior'), ('G', 'Graduate'), ('F', 'Faculty')], help_text='The grade of the student (or faculty status)', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendance_code',
            field=models.CharField(blank=True, help_text='Random attendance code for members to submit to verify their attendance.', max_length=6, null=True),
        ),
    ]
