# Generated by Django 3.0.1 on 2019-12-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_auto_20191223_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the milestone', max_length=200)),
                ('description', models.TextField(help_text='The description of the milestone and what it fully involves.', max_length=10000)),
                ('deadline', models.DateField(help_text='When this milestone should be reached at the latest.')),
                ('complete', models.BooleanField(default=False, help_text='Whether this milestone has been achieved yet.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
