# Generated by Django 3.0.1 on 2019-12-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0018_roadmapmilestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='The first day of the school year.')),
                ('end_date', models.DateField(help_text='The last day of the school year.')),
            ],
        ),
    ]
