# Generated by Django 3.0.1 on 2019-12-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0020_eventrsvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='presentation_link',
        ),
        migrations.AddField(
            model_name='event',
            name='presentation_id',
            field=models.URLField(blank=True, help_text='(optional) The ID of the Google Slides slideshow.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail_link',
            field=models.URLField(blank=True, help_text='An optional link to an image to show for the event. If a slideshow is associated with the event, it will automatically use the slide thumbnail.', null=True),
        ),
    ]
