# Generated by Django 3.0.1 on 2019-12-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0022_auto_20191226_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumbnail_link',
            field=models.URLField(blank=True, help_text='An optional link to an image to show for the event. If a slideshow is associated with the event, it will automatically use the slide thumbnail.', max_length=500, null=True),
        ),
    ]
