# Generated by Django 3.0.1 on 2020-01-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0025_auto_20191230_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='review',
            field=models.TextField(blank=True, help_text='A review after the event concludes covering how the event went, turn out, issues faced, etc. for future leaders to read and take into account.', max_length=10000, null=True),
        ),
    ]
