# Generated by Django 3.0.2 on 2020-01-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0027_auto_20200108_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='school_username',
            field=models.CharField(blank=True, help_text='The username of the student/faculty member of the school.', max_length=100, null=True),
        ),
    ]
