# Generated by Django 3.0.2 on 2020-01-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0029_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(help_text='The answer.', max_length=2000),
        ),
    ]
