# Generated by Django 3.0.2 on 2020-01-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0030_auto_20200109_0957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='FAQ',
        ),
    ]
