# Generated by Django 3.0.2 on 2020-01-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0031_auto_20200109_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, help_text='The answer.', max_length=2000, null=True),
        ),
    ]
