# Generated by Django 3.0.2 on 2020-01-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0032_auto_20200109_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='verified',
            field=models.BooleanField(default=False, help_text='Whether the user has verified their school username or not. True means that they are a real club member.'),
        ),
    ]
