# Generated by Django 3.0.2 on 2020-01-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0034_member_verification_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': ['start'], 'ordering': ['-start']},
        ),
        migrations.AddField(
            model_name='event',
            name='what_to_bring',
            field=models.CharField(blank=True, help_text='An optional description of items members should bring, e.g. laptop and notebook', max_length=500, null=True),
        ),
    ]
