# Generated by Django 3.0.2 on 2020-01-19 19:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0036_eventagendaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('D', 'Dietary Restriction'), ('S', 'Skill')], help_text='The type of tag.', max_length=1)),
                ('title', models.CharField(max_length=50)),
                ('members', models.ManyToManyField(related_name='tags', to='club.Member')),
            ],
            managers=[
                ('skills', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, help_text='Optional comment for members to address anything else.', max_length=1000, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='club.Event')),
            ],
        ),
    ]
