# Generated by Django 3.0.2 on 2020-01-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0038_auto_20200119_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile-images'),
        ),
    ]
