# Generated by Django 3.0.2 on 2020-01-30 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0039_auto_20200129_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfeedback',
            name='date_time_rating',
            field=models.IntegerField(choices=[(1, 'Horrible'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Great')], default=3, help_text='The subjective rating of the date and time of the event.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='food_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Horrible'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Great')], null=True),
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='location_rating',
            field=models.IntegerField(choices=[(1, 'Horrible'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Great')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='overall_rating',
            field=models.IntegerField(choices=[(1, 'Horrible'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Great')], default=3, help_text='The subjective rating of the whole event in general.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='pacing_rating',
            field=models.IntegerField(choices=[(1, 'Horrible'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Great')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='speaker_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Horrible'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Great')], null=True),
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_feedback', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='comments',
            field=models.TextField(blank=True, help_text='Optional comment for members to address anything else.', max_length=2000, null=True),
        ),
    ]
