# Generated by Django 3.0.2 on 2020-02-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0041_auto_20200210_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('IS', 'Info Session'), ('SJ', 'Study Jam'), ('OH', 'Office Hours'), ('HO', 'Hands-on Workshop'), ('HA', 'Hackathon'), ('SS', 'Speaker Session'), ('SC', 'Showcase'), ('CT', 'Core Team Meeting')], help_text='Whether the event is a Workshop, Info session, etc.', max_length=2),
        ),
    ]
