# Generated by Django 3.0.2 on 2020-02-18 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0042_auto_20200210_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 18, 17, 55, 43, 138669, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
