# Generated by Django 3.0.2 on 2020-02-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0043_auto_20200218_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='visibility',
        ),
    ]
