# Generated by Django 3.0.2 on 2020-02-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0044_remove_event_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfeedback',
            name='date_time_rating',
            field=models.IntegerField(choices=[(5, 'Great'), (4, 'Good'), (3, 'Okay'), (2, 'Bad'), (1, 'Horrible')], help_text='The subjective rating of the date and time of the event.'),
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='food_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Great'), (4, 'Good'), (3, 'Okay'), (2, 'Bad'), (1, 'Horrible')], null=True),
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='location_rating',
            field=models.IntegerField(choices=[(5, 'Great'), (4, 'Good'), (3, 'Okay'), (2, 'Bad'), (1, 'Horrible')]),
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='overall_rating',
            field=models.IntegerField(choices=[(5, 'Great'), (4, 'Good'), (3, 'Okay'), (2, 'Bad'), (1, 'Horrible')], help_text='The subjective rating of the whole event in general.'),
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='pacing_rating',
            field=models.IntegerField(choices=[(5, 'Great'), (4, 'Good'), (3, 'Okay'), (2, 'Bad'), (1, 'Horrible')]),
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='speaker_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Great'), (4, 'Good'), (3, 'Okay'), (2, 'Bad'), (1, 'Horrible')], null=True),
        ),
    ]
